name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup lib
      run: |
        vcpkg update
        vcpkg install glfw3:x64-windows
        vcpkg integrate install

    - name: cmake build
      run: |
        mkdir build
        cd  build
        cmake ../ -G "Visual Studio 17" -A x64 -DFTDI_D2XX_ROOT="../third_party/ftdi/windows" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        cmake --build . --target ALL_BUILD --config Release
        cmake --build . --target ALL_BUILD --config Debug
